

import { ScenarioTemplate } from '@/types';

export const SCENARIOS: ScenarioTemplate[] = [
  {
    id: 'low-risk',
    name: 'Low Risk',
    description: 'Mild headache with normal vitals. No severe symptoms.',
    expectedRouting: 'SELF_CARE',
    expectedRiskLevel: 'LOW',
    initialState: {
      patient_name: 'Sarah Mitchell',
      age: 32,
      symptoms: ['Mild headache'],
      symptom_severity: 'MILD',
      heart_rate: 72,
      respiratory_rate: 16,
      oxygen_saturation: 98,
      temperature: 36.8,
      systolic_blood_pressure: 118,
      diastolic_blood_pressure: 76,
      consciousness: 'ALERT',
      chest_pain: false,
      breathing_difficulty: 'NONE',
      bleeding: 'NONE',
    },
  },
  {
    id: 'moderate-risk',
    name: 'Moderate Risk',
    description: 'Moderate fever with slightly elevated vitals.',
    expectedRouting: 'ROUTINE_CLINIC',
    expectedRiskLevel: 'MODERATE',
    initialState: {
      patient_name: 'James Rodriguez',
      age: 45,
      symptoms: ['Fever', 'Body aches', 'Fatigue'],
      symptom_severity: 'MODERATE',
      heart_rate: 96,
      respiratory_rate: 20,
      oxygen_saturation: 96,
      temperature: 38.5,
      systolic_blood_pressure: 135,
      diastolic_blood_pressure: 85,
      consciousness: 'ALERT',
      chest_pain: false,
      breathing_difficulty: 'NONE',
      bleeding: 'NONE',
    },
  },
  {
    id: 'high-risk',
    name: 'High Risk',
    description: 'Significant symptoms with concerning vital signs.',
    expectedRouting: 'URGENT_CLINIC',
    expectedRiskLevel: 'HIGH',
    initialState: {
      patient_name: 'David Chen',
      age: 58,
      symptoms: ['Chest pain', 'Shortness of breath'],
      symptom_severity: 'SEVERE',
      heart_rate: 112,
      respiratory_rate: 26,
      oxygen_saturation: 92,
      temperature: 37.2,
      systolic_blood_pressure: 165,
      diastolic_blood_pressure: 95,
      consciousness: 'ALERT',
      chest_pain: true,
      breathing_difficulty: 'MODERATE',
      bleeding: 'NONE',
    },
  },
  {
    id: 'critical-risk',
    name: 'Critical',
    description: 'Severe symptoms with multiple critical indicators.',
    expectedRouting: 'EMERGENCY',
    expectedRiskLevel: 'CRITICAL',
    initialState: {
      patient_name: 'Margaret Thompson',
      age: 72,
      symptoms: ['Severe chest pain', 'Severe breathing difficulty', 'Dizziness'],
      symptom_severity: 'SEVERE',
      heart_rate: 145,
      respiratory_rate: 32,
      oxygen_saturation: 86,
      temperature: 39.5,
      systolic_blood_pressure: 88,
      diastolic_blood_pressure: 55,
      consciousness: 'DROWSY',
      chest_pain: true,
      breathing_difficulty: 'SEVERE',
      bleeding: 'NONE',
    },
  },
  {
    id: 'contradictory-case',
    name: 'Contradictory Case',
    description: 'Initially reassuring, later reports significantly worse symptoms.',
    expectedRouting: 'HUMAN_REVIEW',
    expectedRiskLevel: 'HIGH',
    initialState: {
      patient_name: 'Robert Williams',
      age: 50,
      symptoms: ['Chest discomfort'],
      symptom_severity: 'MILD',
      heart_rate: 82,
      respiratory_rate: 18,
      oxygen_saturation: 97,
      temperature: 37.0,
      systolic_blood_pressure: 128,
      diastolic_blood_pressure: 82,
      consciousness: 'ALERT',
      chest_pain: false,
      breathing_difficulty: 'NONE',
      bleeding: 'NONE',
    },
  },
  {
    id: 'custom',
    name: 'Custom Synthetic Patient',
    description: 'Start with no preset data. The agent will ask everything from scratch.',
    expectedRouting: 'PENDING',
    expectedRiskLevel: 'UNKNOWN',
    initialState: {},
  },
];